version: '3'
services:
  frontend:
    build: .
    command: npm run dev
    ports:
      - '3000:3000'
    depends_on:
      - db
  backend:
    build: .
    command: npm run node_start
    ports:
      - '3100:3100'
    depends_on:
      - db
    environment:
      - MONGODB_URI=mongodb+srv://minashady12:s4oLzT5OnQjUPT0K@nawy.cjgbqqc.mongodb.net/?retryWrites=true&w=majority&appName=Nawy
  db:
    image: mongo:latest
    volumes:
      - mongodb_data_container:/data/db
volumes:
  mongodb_data_container:
